### ISSUE TITLE
I'm facing errors.

### ISSUE THREAD

**Issue by UniverseCodex01** [zjyzip/AdClose#1]
Logs:

AdClose app only save traffic logs when app it's opened on the foreground at the same time with configured apps. If not all Traffic logs lists will be empty all the time. 

Background settings:

Also I have AdClose on "Not Optimized" list, app is locked on  recent list and has "No restrictions" on miui battery settings, also is configured on Customiuizer to avoid be killed by miui battery saver and avoiding all of this settings, I still getting ads if I don't open AdClose and configured app at the same moment, if I only open configured app, ads will appear after some minutes.

Miui 12.5.3 based on Android 10

**Comment by zjyzip** [comment]
Xposed module does not occupy the backend, real-time access to get data of course in the foreground.
