### ISSUE TITLE
应用在打开后变得很卡

### ISSUE THREAD

**Issue by M100816** [zjyzip/AdClose#2]
Redmi k60 Ultra
HyperOS
小米商城5.19.0
ADClose1.5.8
在打开功能之后拦截列表显示并未拦截任何IP 但小米商城变得非常卡顿 基本要10秒左右才能加载 关闭之后则很流畅

**Comment by zjyzip** [comment]
修了，下次更新就好了

**Comment by M100816** [comment]
更新至1.5.9之后 小米商城、哔哩哔哩、饿了么均无法打开 需要在lsp里关闭才可以获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 Reese_zip ***@***.***>发送时间: 星期日, 二月 4, 2024 11:52:37 下午收件人: zjyzip/AdClose ***@***.***>抄送: 100816 ***@***.***>; Author ***@***.***>主题: Re: [zjyzip/AdClose] 应用在打开后变得很卡 (Issue #2)
修了，下次更新就好了
