### ISSUE TITLE
1.5.9版本出现闪退问题

### ISSUE THREAD

**Issue by M100816** [zjyzip/AdClose#3]
Redmi k60 Ultra
HyperOS1.0.7
小米商城5.19.0 哔哩哔哩7.66.0 饿了么11.7.88
ADClose1.5.8
更新至1.5.9之后 小米商城、哔哩哔哩、饿了么均无法打开 需要在lsp里关闭才可以

**Comment by zjyzip** [comment]
找找自己的原因，不知道

**Comment by zjyzip** [comment]
试试1.6.0
