### ISSUE TITLE
I'm getting ads.

### ISSUE THREAD

**Issue by UniverseCodex01** [zjyzip/AdClose#7]
If module works on real time why I'm getting ads? If I doesn't open module app and configured app at the same time I will get ads on a random moment. Module it's useless, it's the same to use Adguard and adguard works better. I reported this and I was ignored. I use pixelify module to get Unlimited storage on Google photos and I don't need to open Pixelify app every time that I open GPhotos. Fix it or or ignore but says that it's your module issue and you won't fix it because you doesn't want to fix it.

**Comment by zjyzip** [comment]
Fuck you.
